# Generated by Django 5.0.6 on 2024-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_txt', models.CharField(max_length=200, verbose_name='Small title')),
                ('name', models.TextField(verbose_name='Title')),
                ('txt', models.TextField(verbose_name='Text')),
                ('img', models.ImageField(upload_to='archive', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Cover',
            },
        ),
    ]
