# Generated by Django 5.0.6 on 2024-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='img',
            field=models.ImageField(upload_to='archive', verbose_name='Foto:530x300'),
        ),
    ]
