# Generated by Django 5.0.6 on 2024-06-25 21:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='name',
            field=ckeditor.fields.RichTextField(verbose_name='Title'),
        ),
    ]
