# Generated by Django 5.0.6 on 2024-06-25 21:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cover_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='name',
            field=ckeditor.fields.RichTextField(verbose_name='Title (underline)'),
        ),
    ]
